const path = require("path");
const fs   = require("fs");
const { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, AlignmentType, WidthType, ShadingType, BorderStyle, TableLayoutType, VerticalAlign, PageBreak } = require("./backend/node_modules/docx");
const MAROON="800000",WHITE="FFFFFF",ZEBRA_A="FDFBF7",ZEBRA_B="FFFFFF",BC="CCCCCC";
const tB=()=>({top:{style:BorderStyle.SINGLE,size:4,color:BC},bottom:{style:BorderStyle.SINGLE,size:4,color:BC},left:{style:BorderStyle.SINGLE,size:4,color:BC},right:{style:BorderStyle.SINGLE,size:4,color:BC}});
const R=(t,o={})=>new TextRun({text:t,size:17,color:"1A1A1A",...o});
const WR=(t,o={})=>new TextRun({text:t,size:17,color:WHITE,bold:true,...o});
function P(runs,al=AlignmentType.LEFT,sp={}){return new Paragraph({children:runs,alignment:al,spacing:{before:40,after:40,...sp}});}
function BUL(txt){return new Paragraph({children:[R("• ",{color:MAROON,bold:true}),R(txt)],indent:{left:180},spacing:{before:20,after:20}});}
function SH(txt){return new Paragraph({children:[new TextRun({text:txt,bold:true,size:26,color:WHITE})],shading:{type:ShadingType.CLEAR,color:"auto",fill:MAROON},spacing:{before:320,after:200},indent:{left:100}});}
function SUB(txt){return new Paragraph({children:[new TextRun({text:txt,bold:true,size:22,color:MAROON})],spacing:{before:280,after:140}});}
function HR(cols){return new TableRow({tableHeader:true,children:cols.map(({label,w})=>new TableCell({children:[P([WR(label)],AlignmentType.CENTER)],shading:{type:ShadingType.CLEAR,color:"auto",fill:MAROON},borders:tB(),verticalAlign:VerticalAlign.CENTER,width:w?{size:w,type:WidthType.DXA}:undefined}))});}
const PB=[
{id:"PB001",epic:"Authentication & RBAC Governance",role:"Public User",story:"As a public visitor, I want to browse and search the thesis repository without logging in, so that I can access academic research freely.",ac:["GET /api/theses returns 200 OK for unauthenticated requests — no Authorization header required.","Navbar hides Upload, Accounts, Profile links for public users.","AI Gap Analysis button renders for public (canUseAi = !isAdmin, RepositoryPage.jsx line 21).","RepositoryPage renders correctly with thesesList prop from App.jsx fetchTheses()."],pr:"Must Have",st:"Done"},
{id:"PB002",epic:"Authentication & RBAC Governance",role:"Faculty Adviser / Administrator",story:"As a Faculty Adviser or Administrator, I want to log in with my institutional email and password to access elevated capabilities.",ac:["POST /api/auth/login returns JWT (8 h expiry) with { id, email, role, full_name } payload.","bcryptjs comparison used — plaintext passwords never stored.","2-second Authenticating session spinner before onLoginSuccess fires (AuthModal.jsx line 45).","JWT stored in localStorage keys siyasat_token and siyasat_user.","Session restored on reload ONLY for ADMIN / ADVISER (getValidSessionUser, App.jsx line 55)."],pr:"Must Have",st:"Done"},
{id:"PB003",epic:"Authentication & RBAC Governance",role:"Administrator",story:"As an Administrator, I want accounts locked after 5 consecutive failed login attempts to protect against brute-force attacks.",ac:["users table: failed_login_attempts INT, lockout_until TIMESTAMP columns.","After 5 failures: lockout_until = NOW()+15 min; failed_login_attempts resets to 0.","Locked users receive HTTP 403 with remaining minutes in message body.","BLOCKED accounts receive HTTP 403 Account is blocked. Contact administrator.","Successful login resets failed_login_attempts = 0 and lockout_until = NULL."],pr:"Must Have",st:"Done"},
{id:"PB004",epic:"Authentication & RBAC Governance",role:"System",story:"As the system, I want the /profile route guarded against zombie sessions so unauthenticated direct-URL access is safely redirected.",ac:["ProtectedRoute wraps ProfilePage with isAllowed={!!currentUser}.","onDenied fires window.location.replace('/') — hard redirect, no history pollution.","JWT exp claim decoded client-side in getValidSessionUser; expired tokens auto-purged.","STUDENT role session NOT restored on reload (whitelist: ADMIN, ADVISER only)."],pr:"Must Have",st:"Done"},
{id:"PB005",epic:"Authentication & RBAC Governance",role:"Administrator",story:"As an Administrator, I want Delete buttons exclusively on my account so advisers cannot accidentally remove records.",ac:["Delete button renders only when isAdmin === true (RepositoryPage.jsx line 370).","DELETE /api/theses/:id returns HTTP 403 if req.user.role !== ADMIN (server.js line 584).","Advisers see Edit button but not Delete.","fetchTheses() called after deletion to reactively refresh the list."],pr:"Must Have",st:"Done"},
{id:"PB006",epic:"Authentication & RBAC Governance",role:"Administrator",story:"As an Administrator, I want an Accounts Management page to change user roles and block/unblock accounts.",ac:["GET /api/admin/users returns all users ordered by id ASC (ADMIN JWT required).","PUT /api/admin/users/:id/role updates role field.","PUT /api/admin/users/:id/status updates status (ACTIVE / BLOCKED).","AccountsPage.jsx renders only when activePage === users && currentUser?.role === ADMIN."],pr:"Must Have",st:"Done"},
{id:"PB007",epic:"Multi-Attribute Keyword Search",role:"Public User / Researcher",story:"As a researcher, I want to search by keyword and see matches across Title, Abstract, and Keywords to locate relevant studies quickly.",ac:["Backend: ILIKE $1 against title, author, keywords, abstract (server.js line 238).","Frontend: token-based RegExp word-boundary matching (\\b) across combined text fields.","Multi-word queries split on whitespace/comma/semicolon — ALL tokens must match (AND logic).","Empty query returns full list ordered by created_at DESC.","Query synced to URL via window.history.replaceState (key: search)."],pr:"Must Have",st:"Done"},
{id:"PB008",epic:"Multi-Attribute Keyword Search",role:"Public User",story:"As a public user, I want to filter by ABE engineering branch to narrow results to my field of interest.",ac:["Dropdown: Machinery & Power, Land & Water, Structures & Environment, Process Engineering.","Filter uses case-insensitive includes against paper.department or paper.branch.","Correctly combines with active keyword search (AND condition).","Default Category placeholder returns all papers."],pr:"Should Have",st:"Done"},
{id:"PB009",epic:"Multi-Attribute Keyword Search",role:"Public User",story:"As a user navigating from the homepage, I want my search query to carry over to the Repository page automatically.",ac:["initialSearchQuery prop from App.jsx repositorySearchQuery state passed to RepositoryPage.","URL ?search=, ?q=, or ?keyword= parsed on mount via getUrlSearchQuery().","useEffect on initialSearchQuery updates local searchQuery state when prop changes."],pr:"Should Have",st:"Done"},
{id:"PB010",epic:"Repository Sorting & Timestamps",role:"Public User",story:"As a user, I want the thesis list sorted by newest upload date by default so I immediately see the most recently added research.",ac:["Default sortBy = latest; sortPapers() sorts by created_at DESC using Date().getTime().","Backend default: ORDER BY created_at DESC when no sort param provided.","created_at added via ALTER TABLE theses ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP."],pr:"Must Have",st:"Done"},
{id:"PB011",epic:"Repository Sorting & Timestamps",role:"Public User",story:"As a user, I want the upload date shown on each thesis card to assess recency at a glance.",ac:["Timestamp rendered as Uploaded: Sep 22, 2026 using toLocaleDateString({ month:short, day:numeric, year:numeric }).","Graceful fallback to Unknown Date if created_at is null.","Renders in secondary metadata line below thesis title (RepositoryPage.jsx line 389)."],pr:"Should Have",st:"Done"},
{id:"PB012",epic:"Repository Sorting & Timestamps",role:"Public User",story:"As a user, I want additional sort options so I can reorder the repository view to my research needs.",ac:["Sort dropdown: Date Newest First, Date Oldest First, Title A-Z, Title Z-A, Similarity Score.","sortPapers() handles all five cases (RepositoryPage.jsx lines 117-141).","Similarity sort orders by similarity_score DESC from DB column."],pr:"Could Have",st:"Done"},
{id:"PB013",epic:"Local Clustering Engine",role:"System",story:"As the system, I want each uploaded thesis automatically assigned to a thematic cluster using local math so related studies are grouped without API costs.",ac:["computeSimilarityAndCluster() implements Szymkiewicz-Simpson overlap: title x1.5, keywords x1.5, abstract x1.0.","getCleanTokens() applies suffix stemming (ing,ed,ion,s,es,or,ator,ated,ation,er,ive,al,e) + ACADEMIC_STOPWORDS filter.","Similarity >=50% joins matched paper cluster_group; below threshold creates new folder from first keyword + Domain suffix.","cluster_group, similarity_score, matched_thesis_id stored in theses table.","Runs on POST /api/theses and PUT /api/theses/:id with zero external API calls."],pr:"Must Have",st:"Done"},
{id:"PB014",epic:"Local Clustering Engine",role:"Researcher",story:"As a researcher, I want a Folder View displaying theses grouped by auto-detected cluster for thematic exploration.",ac:["Toggle between All Papers list view and Auto-Clustered Folders view.","Folders keyed by cluster_group value from clusteredFolders object.","Each folder shows cluster name, paper count, and average similarity score.","Folders collapsible/expandable by clicking the header row.","Info banner: Similarity evaluated across Title, Abstract, and Keywords."],pr:"Must Have",st:"Done"},
{id:"PB015",epic:"Local Clustering Engine",role:"Administrator",story:"As an Administrator, I want to trigger a full recluster so newly added theses can be retroactively organized.",ac:["POST /api/theses/recluster-all — ADMIN JWT required (403 if not ADMIN).","Iterates all theses ASC by created_at; computeSimilarityAndCluster() applied sequentially.","Batch UPDATE cluster_group, similarity_score, matched_thesis_id for all records.","Returns JSON with count of theses reclustered."],pr:"Should Have",st:"Done"},
{id:"PB016",epic:"Local Clustering Engine",role:"System",story:"As the system, I want a Jaccard-based duplication check before inserting a thesis so near-duplicates are flagged.",ac:["checkForDuplicateThesis() computes Jaccard similarity: title weight 0.65, abstract 0.35.","Exact title match scores 100; substring match scores 90; token Jaccard otherwise.","Score >=30% triggers HTTP 409 Conflict with matched title and similarity score.","User can bypass with Proceed Anyway (ignoreDuplicate = true flag)."],pr:"Must Have",st:"Done"},
{id:"PB017",epic:"Thesis Ingestion & Management",role:"Faculty Adviser / Administrator",story:"As a Faculty Adviser, I want to upload a thesis with a standardized ABE branch classification for correct categorization.",ac:["Department dropdown provides 5 DABE options: Land and Water Resources Engineering; Farm Power and Machinery Engineering; Agricultural Structures and Environmental Control Engineering; Agricultural and Biosystems Processing Engineering Post-Harvest; Agricultural Informatics and Automation.","File upload: PDF only, max 25 MB (multer fileFilter + limits).","Success: HTTP 201 with full inserted thesis record returned.","Duplicate check runs unless ignoreDuplicate = true."],pr:"Must Have",st:"Done"},
{id:"PB018",epic:"Thesis Ingestion & Management",role:"Faculty Adviser / Administrator",story:"As a Faculty Adviser, I want to edit thesis metadata to correct errors after initial upload.",ac:["PUT /api/theses/:id uses parameterized SQL ($1 through $10 or $11) — resolves prior 500 errors from string interpolation.","Re-runs computeSimilarityAndCluster() on updated metadata; persists new cluster assignments.","Optional file replacement: new PDF updates file_path; omitting it preserves existing file.","HTTP 404 if thesis ID not found; 500 with message for any DB error.","EditPaperPage.jsx accessible only to ADMIN / ADVISER (ProtectedRoute wrapper)."],pr:"Must Have",st:"Done"},
{id:"PB019",epic:"Thesis Ingestion & Management",role:"Administrator",story:"As an Administrator, I want to permanently delete a thesis record and its PDF file.",ac:["DELETE /api/theses/:id requires ADMIN JWT (HTTP 403 otherwise).","Associated PDF deleted via fs.unlinkSync() if file exists on disk.","HTTP 404 returned if thesis ID not found.","handleDeletePaper() in App.jsx calls fetchTheses() on success to refresh the list."],pr:"Must Have",st:"Done"},
{id:"PB020",epic:"Thesis Ingestion & Management",role:"Public User / Researcher",story:"As a researcher, I want to download a thesis as PDF from the repository for offline reading.",ac:["GET /api/theses/:id/download serves physical PDF from disk if file_path exists.","Fallback: missing file triggers generatePdfBuffer() raw PDF generation.","Filename sanitized and formatted as Title.pdf for download.","No authentication required — public access."],pr:"Must Have",st:"Done"},
{id:"PB021",epic:"Thesis Ingestion & Management",role:"Faculty Adviser / Administrator",story:"As an Adviser, I want the profile picture upload feature to update my account avatar.",ac:["POST /api/users/profile-picture requires JWT; imageUpload multer (image/* only, 5 MB max).","Path stored in users.profile_image TEXT; returned in login response.","Returns updated user object: id, full_name, email, role, profile_image."],pr:"Could Have",st:"Done"},
{id:"PB022",epic:"AI Gap Analysis & Compliance",role:"Public / Researcher / Faculty Adviser",story:"As a researcher, I want to click AI Analyze Gaps on any thesis and receive 2-3 LLM-identified research gaps.",ac:["POST /api/analyze-gaps sends title, abstract, department, keywords to Groq API (model: openai/gpt-oss-120b).","JSON schema: { gaps: [{ gap_title, description, search_query, local_citations }] }.","Temperature: 0.2; response_format: { type: json_object }.","Each gap enriched with OpenAlex online_references (max 3 per gap, 5 s AbortController timeout).","Local context: 5 most recent theses injected into the system prompt.","Results rendered in right-hand AI panel of RepositoryPage."],pr:"Must Have",st:"Done"},
{id:"PB023",epic:"AI Gap Analysis & Compliance",role:"Administrator",story:"As an Administrator, I want AI Gap Analysis unavailable to my account so it is scoped to researchers only.",ac:["canUseAi = !isAdmin; AI Analyze Gaps button hidden for ADMIN (RepositoryPage.jsx line 21).","POST /api/analyze-single-gap: ADMIN JWT returns HTTP 403 not available for Administrator accounts.","POST /api/theses/:id/analyze-gap: HTTP 403 if req.user.role === ADMIN."],pr:"Must Have",st:"Done"},
{id:"PB024",epic:"AI Gap Analysis & Compliance",role:"Public User / Researcher",story:"As a researcher, I want a prominent Academic AI Advisory banner alongside AI results for critical evaluation.",ac:["Amber advisory banner renders in AI Results panel whenever gaps are displayed.","Banner text advises AI output is research guidance, not authoritative fact.","Styled distinctively (amber background + border + icon) for visual attention."],pr:"Must Have",st:"Done"},
{id:"PB025",epic:"AI Gap Analysis & Compliance",role:"System",story:"As the system, I want global AI gap analysis across the full repository so macro research blind spots can be identified.",ac:["POST /api/analyze-global-gaps fetches 30 most recent theses (abstracts truncated to 650 chars for token budget).","Prompt enforces air-gapped RAG: Do not use external internet browsing or prior knowledge.","Mandates >=20 unique internal citations across identified gaps.","Returns: { analyzed_count, domain_summary, gaps: [{ gap_title, description, supporting_papers }] }."],pr:"Should Have",st:"Done"},
{id:"PB026",epic:"AI Gap Analysis & Compliance",role:"System",story:"As the system, I want GROQ_API_KEY sourced from .env and validated at startup with a clear diagnostic log.",ac:["Startup log: Groq Key Loaded: YES (starts with gsk_...) or NO - KEY MISSING (server.js line 16).","generateAiGaps() throws Error GROQ_API_KEY is not configured if key absent — never silent failure.","GROQ_MODEL configurable via env var; defaults to openai/gpt-oss-120b."],pr:"Must Have",st:"Done"},
];
